"""empty message

Revision ID: 03625e60f931
Revises: c04057dd1da9
Create Date: 2021-08-25 14:44:53.791605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03625e60f931'
down_revision = 'c04057dd1da9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actor', sa.Column('image_url', sa.String(length=128), nullable=True))
    op.add_column('film', sa.Column('year', sa.Integer(), nullable=True))
    op.add_column('film', sa.Column('image_url', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('film', 'image_url')
    op.drop_column('film', 'year')
    op.drop_column('actor', 'image_url')
    # ### end Alembic commands ###
