"""empty message

Revision ID: 58367586902b
Revises: 0bcd1cf0bbfe
Create Date: 2021-08-31 09:21:08.875754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58367586902b'
down_revision = '0bcd1cf0bbfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('film', 'image_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('film', sa.Column('image_url', sa.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###
