"""empty message

Revision ID: c1de6a451490
Revises: 
Create Date: 2021-08-25 09:12:39.778521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1de6a451490'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actor',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actor_name'), 'actor', ['name'], unique=True)
    op.create_table('film',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_film_title'), 'film', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_film_title'), table_name='film')
    op.drop_table('film')
    op.drop_index(op.f('ix_actor_name'), table_name='actor')
    op.drop_table('actor')
    # ### end Alembic commands ###
