"""empty message

Revision ID: dbef325152f1
Revises: 03625e60f931
Create Date: 2021-08-25 17:18:06.894592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbef325152f1'
down_revision = '03625e60f931'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actor', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_actor_timestamp'), 'actor', ['timestamp'], unique=False)
    op.add_column('film', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_film_timestamp'), 'film', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_film_timestamp'), table_name='film')
    op.drop_column('film', 'timestamp')
    op.drop_index(op.f('ix_actor_timestamp'), table_name='actor')
    op.drop_column('actor', 'timestamp')
    # ### end Alembic commands ###
